# Site settings
title: Modern Blog
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Huanghaixia
baseurl: "/huanghaixia.github.io/" # the subpath of your site, e.g. /blog/
url: " https://destinyhhx.github.io/" # the base hostname & protocol for your site
